[tool.poetry]
name = "tastytrade"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
requests = "^2.32.3"
pandas = "^2.2.3"
numpy = "^2.1.3"
jupyter = "^1.1.1"
ipython = "^8.29.0"
matplotlib = "^3.9.2"
seaborn = "^0.13.2"
# Removed types-all
types-Pillow = "^10.0.0"
types-Flask = "^1.1.6"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
ruff = "^0.7.3"
mypy = "^1.13.0"
pytest-cov = "^6.0.0"
pre-commit = "^4.0.1"
pytest-mock = "^3.14.0"
pytest-asyncio = "^0.24.0"
python-dotenv = "^1.0.1"
pandas-stubs = "^2.2.3.241009"
black = "^23.3.0"
isort = "^5.10.1"
flake8 = "^5.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
lint.extend-select = ["E303"]
lint.select = ["E", "F", "W"]
line-length = 100
lint.preview = true

[tool.flake8]
max-line-length = 100
extend-ignore = ["E303"]
